require 'rubygems'
require 'fileutils'
require 'jake'
require 'whenever'

# we need to know what directories contain java application and what are the main classes
java_apps = {
	'test' => 'sk.fiit.plesko.test.MainClass'
}

desc "Compile offline tasks"
task :build do

	FileUtils.mkdir('build')
	java_apps.each_pair do |app_name, mainclass|

		FileUtils.rm_rf Dir.glob(app_name+'/bin/')
		FileUtils.rm_rf Dir.glob(app_name+'/META-INF')
		FileUtils.rm_rf Dir.glob(app_name+'/*.jar')
		
		Javac.in(app_name).execute do |javac|
			javac.src = 'src/**/*.java'
			javac.cp << '.'
			javac.output = 'bin'
		end

		Manifest.in(app_name).execute do |manifest|
			manifest.main_class = mainclass
			manifest.cp = ''
		end

		Jar.in(app_name).execute do |jar|
			jar.name = app_name+'.jar'
			jar.bin << 'bin'
			jar.with_manifest = true
		end

		FileUtils.mv(app_name+'/'+app_name+'.jar', 'build/'+app_name+'.jar')
		
	end
end

task :schedule do
	Whenever::CommandLine.execute({:update=>true})
end
